# Generated by Django 5.2 on 2025-04-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='courts.court'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending Verification'), ('active', 'Active'), ('waiting_validation', 'Waiting Validation'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
