# Generated by Django 5.2 on 2025-04-24 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_court_alter_match_status'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_entries', to='teams.team')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
