# Generated by Django 5.2 on 2025-04-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='waiting_for_court',
            field=models.BooleanField(default=False, help_text='Indicates if match is waiting for a court to become available'),
        ),
    ]
