# Generated by Django 5.2 on 2025-04-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_alter_court_is_active'),
        ('matches', '0004_match_waiting_for_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='proposed_court',
            field=models.ForeignKey(blank=True, help_text='Court proposed by the first activating team when no courts were free', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_matches', to='courts.court'),
        ),
    ]
