# Generated by Django 5.2 on 2025-04-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_proposed_court'),
        ('teams', '0001_initial'),
        ('tournaments', '0003_alter_bracket_options_alter_tournamentteam_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchactivation',
            options={'ordering': ['activated_at']},
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.stage'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchactivation',
            name='is_initiator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending Verification'), ('active', 'Active'), ('waiting_validation', 'Waiting Validation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
