# Generated by Django 5.2 on 2025-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_matchactivation_options_match_loser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='role',
            field=models.CharField(choices=[('pointer', 'Pointer'), ('milieu', 'Milieu'), ('tirer', 'Tirer'), ('flex', 'Flex')], default='flex', help_text="Player's role in the match", max_length=10),
        ),
    ]
