# Generated by Django 5.2 on 2025-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_matchplayer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(blank=True, choices=[('doublet', 'Doublet (2 players)'), ('triplet', 'Triplet (3 players)'), ('tete_a_tete', 'Tête-à-tête (1 player)'), ('mixed', 'Mixed Format'), ('unknown', 'Unknown Format')], help_text='Type of match based on player count', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_player_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of players from team 1', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_player_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of players from team 2', null=True),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='match_format',
            field=models.CharField(blank=True, help_text='Format of match this player participated in', max_length=20, null=True),
        ),
    ]
