# Generated by Django 5.2 on 2025-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_match_type_match_team1_player_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='role',
            field=models.CharField(choices=[('pointer', 'Pointer'), ('milieu', 'Milieu'), ('tirer', 'Shooter'), ('flex', 'Flex')], default='flex', help_text="Player's role in the match", max_length=10),
        ),
    ]
