# Generated by Django 5.2 on 2025-06-03 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_playerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_subteam',
            field=models.BooleanField(default=False, help_text='True if this team is a subteam of another team'),
        ),
        migrations.AddField(
            model_name='team',
            name='parent_team',
            field=models.ForeignKey(blank=True, help_text='Parent team if this is a subteam', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subteams', to='teams.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='subteam_type',
            field=models.CharField(blank=True, choices=[('triplet', 'Triplet'), ('doublette', 'Doublette'), ('tete_a_tete', 'Tête-à-tête')], help_text='Type of subteam (triplet, doublette, etc.)', max_length=20, null=True),
        ),
    ]
