# Generated by Django 5.2 on 2025-06-18 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_is_subteam_team_parent_team_team_subteam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='rating_history',
            field=models.JSONField(blank=True, default=list, help_text='History of rating changes with timestamps and match details'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='value',
            field=models.FloatField(default=100.0, help_text='Dynamic rating value (starts at 100.0)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
