# Generated by Django 5.2 on 2025-06-20 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_add_dynamic_rating_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_svg', models.FileField(blank=True, help_text='Team logo in SVG format (vector graphics, scalable)', null=True, upload_to='team_logos/')),
                ('team_photo_jpg', models.ImageField(blank=True, help_text='Team photo in JPG format (group photo, team picture)', null=True, upload_to='team_photos/')),
                ('team_value', models.FloatField(default=100.0, help_text='Dynamic team rating value (starts at 100.0, like player ratings)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('value_history', models.JSONField(blank=True, default=list, help_text='History of team value changes with timestamps and match details')),
                ('badges', models.JSONField(blank=True, default=list, help_text='List of earned badges (tournament wins, achievements, milestones)')),
                ('achievements', models.JSONField(blank=True, default=dict, help_text='Achievement data and progress tracking')),
                ('is_friendly_team', models.BooleanField(default=False, help_text='True if this profile belongs to the existing Friendly Team (read-only identification)')),
                ('profile_type', models.CharField(choices=[('full', 'Full Profile'), ('sub_team', 'Sub-team Profile'), ('friendly', 'Friendly Team Profile'), ('minimal', 'Minimal Profile')], default='full', help_text='Type of profile for different team categories', max_length=20)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('tournaments_participated', models.PositiveIntegerField(default=0)),
                ('tournaments_won', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='Team description, motto, or about information', null=True)),
                ('founded_date', models.DateField(blank=True, help_text='Date when the team was founded', null=True)),
                ('motto', models.CharField(blank=True, help_text='Team motto or slogan', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Profile',
                'verbose_name_plural': 'Team Profiles',
            },
        ),
    ]
