# Generated by Django 5.2 on 2025-06-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_teamprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the sub-team (e.g., 'Triplet A', 'Doublette 1')", max_length=50)),
                ('sub_team_type', models.CharField(choices=[('triplet', 'Triplet (3 players)'), ('doublette', 'Doublette (2 players)'), ('tete_a_tete', 'Tête-à-tête (1 player)'), ('custom', 'Custom')], default='triplet', help_text='Type of sub-team formation', max_length=20)),
                ('max_players', models.PositiveIntegerField(default=3, help_text='Maximum number of players allowed in this sub-team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_team', models.ForeignKey(help_text='The main team this sub-team belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sub_teams', to='teams.team')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('parent_team', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubTeamPlayerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('tirer', 'Tireur'), ('pointeur', 'Pointeur'), ('milieu', 'Milieu'), ('any', 'Any Position')], default='any', help_text="Player's position in this sub-team", max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_team_assignments', to='teams.player')),
                ('sub_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_assignments', to='teams.subteam')),
            ],
            options={
                'ordering': ['assigned_at'],
                'unique_together': {('sub_team', 'player')},
            },
        ),
    ]
