# Generated by Django 5.2 on 2025-04-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='court',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='court',
            name='location',
        ),
        migrations.RemoveField(
            model_name='court',
            name='name',
        ),
        migrations.RemoveField(
            model_name='court',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='courtassignment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='courtassignment',
            name='start_time',
        ),
        migrations.AddField(
            model_name='court',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourtAvailability',
        ),
    ]
