# Generated by Django 5.2 on 2025-04-24 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_alter_court_options_remove_court_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourtAssignment',
        ),
    ]
