# Generated by Django 5.2 on 2025-04-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_delete_courtassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If True, court is currently in use by a match'),
        ),
    ]
