# Generated by Django 5.2 on 2025-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_alter_court_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='location_description',
            field=models.TextField(blank=True, help_text="Description of the court's location"),
        ),
        migrations.AddField(
            model_name='court',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for the court (e.g., Main Court)', max_length=100),
        ),
    ]
