# Generated by Django 5.2 on 2025-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_courtcomplex_court_court_complex_courtcomplexphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='court_complex',
        ),
        migrations.AddField(
            model_name='courtcomplex',
            name='courts',
            field=models.ManyToManyField(blank=True, help_text='Courts assigned to this complex', to='courts.court'),
        ),
    ]
