# Generated by Django 5.2 on 2025-06-03 16:50

import django.db.models.deletion
import friendly_games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_playerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCodename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(default=friendly_games.models.generate_codename, help_text='Unique 6-character alphanumeric code for friendly game verification', max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codename_profile', to='teams.player')),
            ],
            options={
                'verbose_name': 'Player Codename',
                'verbose_name_plural': 'Player Codenames',
            },
        ),
    ]
