# Generated by Django 5.2 on 2025-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly_games', '0002_friendlygame_friendlygamestatistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlygame',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this match number expires', null=True),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='match_number',
            field=models.CharField(blank=True, help_text='4-digit match number for joining', max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='validation_status',
            field=models.CharField(choices=[('NOT_VALIDATED', 'Not Validated'), ('PARTIALLY_VALIDATED', 'Partially Validated'), ('FULLY_VALIDATED', 'Fully Validated')], default='NOT_VALIDATED', help_text='Validation level based on codename usage', max_length=20),
        ),
        migrations.AlterField(
            model_name='friendlygame',
            name='game_pin',
            field=models.CharField(blank=True, help_text='Legacy 6-digit PIN for this game', max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='friendlygame',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_FOR_PLAYERS', 'Waiting for Players'), ('READY', 'Ready to Play'), ('ACTIVE', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='friendlygameplayer',
            name='position',
            field=models.CharField(choices=[('TIRER', 'Tirer'), ('POINTEUR', 'Pointeur'), ('MILIEU', 'Milieu')], max_length=10),
        ),
    ]
