# Generated by Django 5.2 on 2025-06-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly_games', '0003_friendlygame_expires_at_friendlygame_match_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlygame',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_FOR_PLAYERS', 'Waiting for Players'), ('READY', 'Ready to Play'), ('ACTIVE', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='WAITING_FOR_PLAYERS', max_length=20),
        ),
    ]
