# Generated by Django 5.2 on 2025-06-03 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly_games', '0004_alter_friendlygame_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by_team', models.CharField(choices=[('BLACK', 'Black Team'), ('WHITE', 'White Team')], help_text='Which team submitted the result', max_length=10)),
                ('validated_by_team', models.CharField(blank=True, choices=[('BLACK', 'Black Team'), ('WHITE', 'White Team')], help_text='Which team validated the result', max_length=10, null=True)),
                ('validation_action', models.CharField(blank=True, choices=[('agree', 'Agree with Result'), ('disagree', 'Disagree with Result')], help_text='Action taken by validating team', max_length=10, null=True)),
                ('submitter_codename', models.CharField(blank=True, help_text='Codename of player who submitted result', max_length=6)),
                ('validator_codename', models.CharField(blank=True, help_text='Codename of player who validated result', max_length=6)),
                ('submitter_verified', models.BooleanField(default=False, help_text='Whether submitter codename was verified')),
                ('validator_verified', models.BooleanField(default=False, help_text='Whether validator codename was verified')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the result')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='friendly_games.friendlygame')),
            ],
            options={
                'verbose_name': 'Friendly Game Result',
                'verbose_name_plural': 'Friendly Game Results',
            },
        ),
    ]
