# Generated by Django 5.2 on 2025-04-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0002_tournament_has_doublets_tournament_has_tete_a_tete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTournamentSignin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_in_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_signins', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_signins', to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('team', 'tournament')},
            },
        ),
    ]
