# Generated by Django 5.2 on 2025-04-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='has_doublets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='has_tete_a_tete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='has_triplets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='play_format',
            field=models.CharField(choices=[('triplets', 'Triplets (3 players)'), ('doublets', 'Doublets (2 players)'), ('tete_a_tete', 'Tête-à-tête (1 player)'), ('mixed', 'Mixed Formats')], max_length=20),
        ),
        migrations.CreateModel(
            name='TournamentCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'court')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='courts',
            field=models.ManyToManyField(through='tournaments.TournamentCourt', to='courts.court'),
        ),
    ]
