# Generated by Django 5.2 on 2025-04-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_has_doublets_tournament_has_tete_a_tete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracket',
            options={'ordering': ['round__number', 'position']},
        ),
        migrations.AlterModelOptions(
            name='tournamentteam',
            options={'ordering': ['tournament', 'seeding_position', 'team__name']},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='number_of_rounds',
        ),
        migrations.AddField(
            model_name='round',
            name='number_in_stage',
            field=models.PositiveIntegerField(blank=True, help_text='Round number within the current stage (if multi-stage)', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_multi_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='current_stage_number',
            field=models.PositiveIntegerField(default=1, help_text='The current stage number the team is participating in'),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the team is currently active in the tournament (not eliminated)'),
        ),
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.PositiveIntegerField(help_text='Overall round number in the tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('swiss', 'Swiss System'), ('multi_stage', 'Multi-Stage')], default='knockout', max_length=20),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('format', models.CharField(choices=[('swiss', 'Swiss System'), ('poule', 'Poules/Groups'), ('knockout', 'Knockout'), ('round_robin', 'Round Robin')], max_length=20)),
                ('num_qualifiers', models.PositiveIntegerField(help_text='Number of teams advancing FROM this stage (0 for final stage)')),
                ('num_rounds_in_stage', models.PositiveIntegerField(default=1, help_text='Number of rounds within this stage (e.g., for Swiss)')),
                ('is_complete', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['stage_number'],
                'unique_together': {('tournament', 'stage_number')},
            },
        ),
        migrations.AddField(
            model_name='bracket',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.stage'),
        ),
        migrations.AddField(
            model_name='round',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.stage'),
        ),
    ]
