# Generated by Django 5.2 on 2025-04-29 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_bracket_options_alter_tournamentteam_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentteam',
            options={'ordering': ['seeding_position']},
        ),
        migrations.AlterUniqueTogether(
            name='bracket',
            unique_together={('round', 'position')},
        ),
        migrations.RemoveField(
            model_name='tournamentteam',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='tournamentteam',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='tournamentcourt',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='number_in_stage',
            field=models.PositiveIntegerField(default=1, help_text='Round number within the current stage'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='current_stage_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='stage',
        ),
    ]
