# Generated by Django 5.2 on 2025-05-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournamentteam_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracket',
            options={'ordering': ['round', 'position']},
        ),
        migrations.RenameField(
            model_name='round',
            old_name='is_completed',
            new_name='is_complete',
        ),
        migrations.AlterUniqueTogether(
            name='bracket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bracket',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bracket',
            name='parent_bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_brackets', to='tournaments.bracket'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.stage'),
        ),
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='allowed_match_types',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for allowed match types (doublet, triplet, tete_a_tete) and mixed matches'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='position',
            field=models.PositiveIntegerField(help_text='Position in the bracket (e.g., 1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.round'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='round',
            name='number_in_stage',
            field=models.PositiveIntegerField(default=1, help_text='Round number within the current stage'),
        ),
        migrations.AlterUniqueTogether(
            name='bracket',
            unique_together={('tournament', 'round', 'position')},
        ),
    ]
