# Generated by Django 5.2 on 2025-06-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0006_courtcomplex_court_court_complex_courtcomplexphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_entries_per_day', models.IntegerField(default=2, help_text='Maximum entries per action type per day')),
                ('entry_expiry_hours', models.IntegerField(default=24, help_text='Hours after which entries expire')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable the Billboard module')),
            ],
            options={
                'verbose_name': 'Billboard Settings',
                'verbose_name_plural': 'Billboard Settings',
            },
        ),
        migrations.CreateModel(
            name='BillboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='Player codename (required)', max_length=6)),
                ('action_type', models.CharField(choices=[('AT_COURTS', "I'm at the courts"), ('GOING_TO_COURTS', "I'm going to the courts"), ('LOOKING_FOR_MATCH', 'Looking to complete a PFC tournament match')], max_length=20)),
                ('scheduled_time', models.CharField(blank=True, choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], help_text="For 'going to courts' entries", max_length=5, null=True)),
                ('opponent_team', models.CharField(blank=True, help_text='For tournament match requests', max_length=100, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('court_complex', models.ForeignKey(help_text='Select court complex', on_delete=django.db.models.deletion.CASCADE, to='courts.courtcomplex')),
            ],
            options={
                'verbose_name': 'Billboard Entry',
                'verbose_name_plural': 'Billboard Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillboardResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='Responding player codename', max_length=6)),
                ('response_type', models.CharField(choices=[('JOINING', 'Joining'), ('ACCEPTING', 'Accepting')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='billboard.billboardentry')),
            ],
            options={
                'verbose_name': 'Billboard Response',
                'verbose_name_plural': 'Billboard Responses',
                'ordering': ['-created_at'],
                'unique_together': {('entry', 'codename')},
            },
        ),
    ]
