# Generated by Django 5.2 on 2025-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardentry',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='True when opponent team has confirmed the match'),
        ),
    ]
