# Generated by Django 5.2 on 2025-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_billboardentry_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardentry',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date for scheduled appointments', null=True),
        ),
    ]
